Add discussion of some common Travis errors and fixes
katyhuff/python-testing pull request #14
Opened 2017-04-18 17:11 UTC by andreww

This addresses issue #10. I've added three things to the lesson:

1. A list three reasons why travisCI fails to run tests and
information on how to fix these to discussion.md. These
have all been seen in practice when delivering the lesson.

2. A note the use of https://lint.travis-ci.org/ in 08-ci and
note that the syntax is important.

3. A link from 08-ci to the discussion file, suggesting
that fixes for some errors can be found there.

I also thought about putting the advice in a "solution" div element under the "Add a .travis.yml File" challenge (as a "hint"). However, this is not hidden using the current template. It may be worth revisiting this once the template is updated.

2017-05-04 21:01 UTC, katyhuff requested changes

2017-05-04 21:01 UTC, katyhuff commented on discussion.md
> +lesson is that Travis-CI does not run the tests in the version control
I usually write this as "version-controlled repository" rather than "version control repository"

2017-05-04 21:01 UTC, katyhuff commented on discussion.md
> +minor change to a file, the committing and pushing the change.
then committing

2017-05-04 21:02 UTC, katyhuff commented
Hi @andreww . Thanks for this contribution!!! I think this is great and almost ready to add. I noted two very minor grammatical things above. I hope you won't mind updating your PR. If you do just those two things, I'll be happy to add your contribution.

2017-05-05 08:15 UTC, andreww commented
Thanks for the review. I've fixed these in the PR so hopefully @katyhuff can merge.

2017-05-05 13:23 UTC, katyhuff approved these changes

2017-05-05 13:23 UTC, merged

2017-05-05 13:23 UTC, katyhuff commented
Thanks! I'll need to rebuild and push before the html is online. It'l'l be up shortly. Thanks!